import java.util.Scanner;

public class LotteryUsingStrings {
    public static void main(String[] args) {
        //Generating lottery number
        String lottery = "" + (int)(Math.random()*10) +
                (int)(Math.random()*10);

        //User guess
        Scanner input = new Scanner(System.in);
        System.out.println("Enter your lottery pick (two digits): ");
        String guess = input.nextLine();

        //Get digits from computer lottery
        char digit0 = lottery.charAt(0);
        char digit1 = lottery.charAt(1);

        //Get digits from user input
        char userDigit0 = guess.charAt(0);
        char userDigit1 = guess.charAt(1);

        System.out.println("The lottery number " +
                "generated by machine is: " + lottery);

        //Check the guess
        if(guess.equals(lottery))
            System.out.println("You won the lottery!! " +
                    "Exact Match prize money 10000$");
        else if (userDigit1 == digit0 && userDigit0 == digit1)
            System.out.println("All digits matched! You won 3000$");
        else if (userDigit1 == digit1 || userDigit1 == digit0 ||
                 userDigit0 == digit1 || userDigit0 == digit0)
            System.out.println("Only one digit matched! You won 1000$");
        else
            System.out.println("Sorry! Try again. Better luck next time");

        }

    }
